### ISSUE TITLE
chat user etc 

### ISSUE THREAD

**Issue by hirenmistry17** [adarshbalu/twilio_flutter#1]
This lib provide sendsms, whatsappsms etc, when will it gives "chat with other user", "chat with group", video calling facility

**Comment by adarshbalu** [comment]
Working on it! Contributions also appreciated.

**Comment by wolfenrain** [comment]
Hello, I am one of the maintainers of the [twilio_programmable_video plugin](https://pub.dev/packages/twilio_programmable_video)  for flutter. Thought I dropped by and mention its existence. Love the work you have been doing, keep it up. Just wanted to make sure you were aware of it.

PS(1): We are also working on a programmable chat plugin, will be released soon when we have a proper example running: https://gitlab.com/twilio-flutter/programmable-chat/. Android is pretty much implemented

PS(2): You are also welcome to join our discord if you like, we are always happy to help and discuss code problems :-)

**Comment by adarshbalu** [comment]
> Hello, I am one of the maintainers of the [twilio_programmable_video plugin](https://pub.dev/packages/twilio_programmable_video) for flutter. Thought I dropped by and mention its existence. Love the work you have been doing, keep it up. Just wanted to make sure you were aware of it.
> 
> PS(1): We are also working on a programmable chat plugin, will be released soon when we have a proper example running: https://gitlab.com/twilio-flutter/programmable-chat/. Android is pretty much implemented
> 
> PS(2): You are also welcome to join our discord if you like, we are always happy to help and discuss code problems :-)

I tried to use the plugin and found it quite complicated for use and i instead used jitsi.
I'm currently working on another project.

**Comment by wolfenrain** [comment]
Hmm in what way did you find it complicated? We tried to follow both the official Twilio documentation and SDK api naming conventions. So that people who have had experience with their SDKs are able to easily implement it in flutter.

If you want you can join our discord to discuss this further, considering your project is not the best place to discuss another project haha

**Comment by adarshbalu** [comment]
Yeah.
