### ISSUE TITLE
Help with Documentation

### ISSUE THREAD

**Issue by adarshbalu** [adarshbalu/twilio_flutter#11]
Help with documentation of the package is very much appreciated. Comment if interested in helping me out.

**Comment by thameemkj** [comment]
Im interested. How can i help you ?

**Comment by adarshbalu** [comment]
> Im interested. How can i help you ?

Have a look at the code. You can help me with better documentation of the package.

**Comment by adarshbalu** [comment]
> Oh you mean documentation within the code, ryt ?

Yes. And also the readme can be improved.

**Comment by thameemkj** [comment]
Sure i'll try.
