### ISSUE TITLE
Check response after sending SMS

### ISSUE THREAD

**Issue by SilenceCodder** [adarshbalu/twilio_flutter#12]
Am trying to check a response either failed or success but It's only displaying in the console. but I can't display it on the UI.

 twilioFlutter.sendSMS(toNumber: '+2349057463831', messageBody: AppString.smsBody, ).then((value){
      print('Value $value'); //Doesnt display
    }).catchError((error){
      print('Catch Error ${error.toString()}'); //Only display "Exception"
    });

**Comment by adarshbalu** [comment]
Try updating to the latest version

**Comment by hftisolu** [comment]
Any update?

**Comment by adarshbalu** [comment]
This issue is fixed as of now. Please re-open with details if there's any problem.
@SilenceCodder
