### ISSUE TITLE
Phone verification

### ISSUE THREAD

**Issue by CSharper63** [adarshbalu/twilio_flutter#13]
Hello, does your package support twilio phone verification in flutter ?

**Comment by adarshbalu** [comment]
Hi, @CSharper63 can you give more details about the requirement?

**Comment by haiderr-nawaz** [comment]
@adarshbalu Phone verification using twillio. Actually there's another package on pub.dev names twillio_phone_verify but they haven't updated the http package which is causing conflicts with other packages.

**Comment by grodnoglobals** [comment]
is this available please

**Comment by adarshbalu** [comment]
Hi @haiderr-nawaz, @grodnoglobals, @CSharper63, This feature will be taken up soon.

**Comment by adarshbalu** [comment]
Added feature in #51
