### ISSUE TITLE
I can't send whatsapp messages.

### ISSUE THREAD

**Issue by patricknicolosi** [adarshbalu/twilio_flutter#14]
I can't send whatsapp messages. The error is "Twilio could not find a Channel with the specified From address
"with error code 63007

**Comment by adarshbalu** [comment]
Sure. WIll look into it.

**Comment by actasape** [comment]
no solution until now ??

**Comment by adarshbalu** [comment]
Hi @patricknicolosi, @actasape this has nothing to do with the package. There must be something wrong with the setup of the Twilio credentials.
