### ISSUE TITLE
Suggestion regarding usage of 'from number'

### ISSUE THREAD

**Issue by thameemkj** [adarshbalu/twilio_flutter#17]
You are taking 'from number' from the constructor itself (I mean during class instantiation), and sendSMS, sendWhatsApp methods are called with parameters 'to' and 'message content'. 
Here the problem is that, if the user has multiple twilio numbers, and wants to send sms and whats app message from different numbers, it will not be possible.
My suggestion is that, take a "from number" during instantiation (as it is now), and provide an optional parameter in the methods to give "from number". And if the optional parameter is null use the number given during instantiation or else use the number in the optional parameter.

**Comment by adarshbalu** [comment]
> You are taking 'from number' from the constructor itself (I mean during class instantiation), and sendSMS, sendWhatsApp methods are called with parameters 'to' and 'message content'. Here the problem is that, if the user has multiple twilio numbers, and wants to send sms and whats app message from different numbers, it will not be possible. My suggestion is that, take a "from number" during instantiation (as it is now), and provide an optional parameter in the methods to give "from number". And if the optional parameter is null use the number given during instantiation or else use the number in the optional parameter.

Thanks for the suggestion. Will surely look into it.

**Comment by thameemkj** [comment]
Okayy.

**Comment by adarshbalu** [comment]
This issue is closed, fix here: #40
