### ISSUE TITLE
"Future getSMSList(String url) async" never returns a list

### ISSUE THREAD

**Issue by rstenberg** [adarshbalu/twilio_flutter#2]
"Future getSMSList(String url) async" in twilio_flutter/lib/models/sms.dart never returns a list. It always returns null because the function does not specify a Future return type.

Please see https://stackoverflow.com/questions/59027206/flutter-async-function-from-a-different-class-prints-okay-but-returns-null for a similar scenario.

**Comment by adarshbalu** [comment]
Thank you. Will resolve.

**Comment by adarshbalu** [comment]
Method deprecated in the latest release. Added another method for the same.
