### ISSUE TITLE
I am trying to send sms in trial version but facing Unhandled Exception: Exception

### ISSUE THREAD

**Issue by irfansadiq786** [adarshbalu/twilio_flutter#22]
I am using this plugin for sending sms in trial version. Whenever I try to send sms to different number other than I added in console, I got an exception which I am unable to handle, I tried wrapping with try, catch block of My code when sending sms so i can catch the exception but failed.
Whenever I call  twilioFlutter.sendSMS method I got an exception and my app crashes.
Here is my Code:
try {
      twilioFlutter.sendSMS(
          toNumber: phoneNumber,
          messageBody: 'Irfan Sadiq is sending message and your code is $otp');
    } catch (e) {
      ScaffoldMessenger.of(context)
          .showSnackBar(const SnackBar(content: Text('Something went wrong')));
    }
Any help, fixes will be highly appreciated. 
Thanks

**Comment by thameemkj** [comment]
@irfansadiq786 
Please check if sendSMS is a future function. If so you'll have to add catchError method to catch exceptions. Or else add an await while calling sendSMS function inorder to get exceptions inside try-catch.

**Comment by adarshbalu** [comment]
Hi @irfansadiq786, will be taking up Exception handling in the next update.
