### ISSUE TITLE
Return status response

### ISSUE THREAD

**Issue by Tahateber95** [adarshbalu/twilio_flutter#5]
I suggest you add a status response to check if the operation went successfully or not.

**Comment by thameemkj** [comment]
@adarshbalu  as @Tahateber95  said , I also suggest you to add return status, or atleast throw an exception if sending message failed. You are just printing the status.

**Comment by jigarfumakiya** [comment]
Yes Please add return status @adarshbalu

**Comment by adarshbalu** [comment]
Yes guys, will surely add that in the next update. If anyone can contribute then please do.

**Comment by jigarfumakiya** [comment]
ok, @adarshbalu Will try.
Thanks

**Comment by adarshbalu** [comment]
Try now it's added
