### ISSUE TITLE
Incorrect request body SMS verification

### ISSUE THREAD

**Issue by SebastianKlaiber** [adarshbalu/twilio_flutter#57]
Hi,

I just tried out the SMS verification, and it seems like there is a small bug in the Implementation. The Fix is quite easy but needs a change in the dart version constraints. 

The channel contains the name of the enum.
`To=...&Channel=verificationchannel.sms`

If it is ok for you, I would create a PR, increase the constraints to dart 2.15.0 and use name instead of the `toString()`. In TwilioVerifyServiceImpl line 47.

**Comment by adarshbalu** [comment]
Hi, @SebastianKlaiber this feature is still under development. It was just released for testing and the related bugs will be fixed in the next release.

**Comment by adarshbalu** [comment]
Closing this as a fix is released, please re-open if the issue persists.
